### ISSUE TITLE
Would love to join you on discord but got "invite invalid"

### ISSUE THREAD

**Issue by lindamacdonald** [snoopForms/snoopforms#1]
hey there guys :)

found you on reactexamples and wanted to join you on discord but couldnt. Just got invite invalid

**Comment by matthiasnannt** [comment]
Hi @lindamacdonald 
thanks for reaching out 😊 You can join our discord here:
https://discord.gg/3YFcABF2Ts

See you on the other side 😅

**Comment by lindamacdonald** [comment]
Thanks a mil am in ☺️☺️

fre. 10. jun. 2022, 03:27 skrev Matthias Nannt ***@***.***>:
