### ISSUE TITLE
make smtp credentials / email verification optional

### ISSUE THREAD

**Issue by matthiasnannt** [snoopForms/snoopforms#26]
let self-hosting snoopHub work without providing SMTP credentials and by that disabling email verification. This lowers the barrier for self-hosting.

**Comment by NeckBeardPrince** [comment]
@matthiasnannt Yes, would be very helpful. I want to demo this locally, and having to tie in an SMTP server is a blocker.

**Comment by timothyde** [comment]
https://github.com/snoopForms/snoopHub/pull/54
