### ISSUE TITLE
Add component import on the snoopHub React quick start guide

### ISSUE THREAD

**Issue by syahzuan** [snoopForms/snoopforms#70]
The React tab on the snoopHub page (i.e. https://app.snoopforms.com/forms/(form_id)/form/react) has 2 steps as a quick start guide.

But step 2 is not working as `import { SnoopForm } from "@snoopforms/react";` is missing. One won't be able to start until diving into the docs to find this import. 

It's perhaps more intuitive to include the import there.

Cheers.

**Comment by matthiasnannt** [comment]
@syahzuan thanks for the issue report 😊 We added the import to the react page 😊
