### ISSUE TITLE
Several Radio Buttons on same page not compatible

### ISSUE THREAD

**Issue by jobenjada** [snoopForms/snoopforms#85]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

If you have more than 1 radio element the selection on the first question does not remain, once you choose an option in the next one. 

### Steps to Reproduce

(Write your answer here.)

## Environment

- [ x] snoopForms Cloud (app.snoopforms.com)

### Additional Context

![several radio elements dont work](https://user-images.githubusercontent.com/72809645/191112925-9c95e2d1-1953-4ae0-b820-0fe688172c5b.gif)

**Comment by matthiasnannt** [comment]
fixed with https://github.com/snoopForms/snoopforms/commit/de8173bc841c7fa04e3a31224e22f652439f29f5
